config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :questions
  resources :projects
  resources :myfiles
  root "projects#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blog.increment!(:views)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :views, :public, :top, :category)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <table>
    <tr>
      <th>标题:</th>
      <td>
        <%= blog.title %>
      </td>
    </tr>

    <tr>
      <th>内容:</th>
      <td>
        <%= blog.content %>
      </td>
    </tr>

    <!--
    <tr>
      <th>浏览:</th>

      <td>
        <%= blog.views %>
      </td>
    </tr>

    <tr>
      <th>公开:</th>
      <td>
        <%= blog.public %>
      </td>
    </tr>

    <tr>
      <th>置顶:</th>

      <td>
        <%= blog.top %>
      </td>
    </tr>
    -->

    <tr>
      <th>Category:</th>
      <td>
        <%= blog.category %>
      </td>
    </tr>
  </table>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :views, style: "display: block" %>
    <%= form.number_field :views %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.label :top, style: "display: block" %>
    <%= form.check_box :top %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>博客</h1>
<%= link_to "新建", new_blog_path %>

<div id="blogs">
  <table>
    <% @blogs.each do |blog| %>
      <tr>
        <td>
          <%= blog.title %>&nbsp; <%= blog.category %>&nbsp; (<%= blog.views %>)
        </td>
        <td>
          <% for blog in @blogs %>
            <div class="blog" data-id="<%= blog.id %>">
              <%= link_to '查看', blog_path(blog) %>
              <span class="views-count"><%= blog.views %></span>
            </div>
          <% end %>
        </td>
      </tr>
    <%#= render blog %>
    <% end %>
  </table>
</div>

<%= link_to "新建", new_blog_path %>
<script>
  $(document).ready(function() {
    $('.blog').click(function() {
      var blogId = $(this).data('id');
      $.ajax({
        url: '/blogs/' + blogId,
        method: 'GET',
        success: function() {
          var viewsCount = $(this).find('.views-count').text();
          var totalViewsCount = $('#total-views-count').text();
          $(this).find('.views-count').text(parseInt(viewsCount) + 1);
          $('#total-views-count').text(parseInt(totalViewsCount) + 1);
        }
      });
    });
  });
</script>

Total views: <span id="total-views-count"><%= Blog.sum(:views) %></span>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>